# Generated by Django 4.1.5 on 2023-01-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre de la carrera', max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=50, verbose_name='nombreEmpresa')),
                ('nombreResponsable', models.CharField(max_length=50, verbose_name='nombreResponsable')),
                ('emailResponsable', models.EmailField(max_length=50, verbose_name='email')),
                ('telefonoResponsable', models.CharField(max_length=50, verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='EmpresaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=50, verbose_name='Enombre')),
                ('nombreProyecto', models.CharField(max_length=50, verbose_name='Pnombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('puesto', models.CharField(help_text='puesto laboral', max_length=50, verbose_name='puesto')),
                ('nombreConsultante', models.CharField(max_length=100, verbose_name='Cnombre')),
                ('telefono', models.CharField(max_length=50, verbose_name='telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'EmpresaSolicitud',
                'verbose_name_plural': 'EmpresaSolicituds',
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePropuesta', models.CharField(max_length=50, verbose_name='nombre')),
                ('descriptionPropuesta', models.TextField(blank=True, verbose_name='Descipcion')),
                ('nombreEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminView.empresa')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='propuestas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminView.propuesta'),
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='nombre del alumno', max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='apellidos del alumno', max_length=100, verbose_name='Apellidos')),
                ('matricula', models.CharField(help_text='Matricula del alumno', max_length=20, verbose_name='Matricula')),
                ('emailAlumno', models.EmailField(help_text=' email del alumno', max_length=254, verbose_name='Email')),
                ('telefonoAlumno', models.CharField(max_length=50, verbose_name='telefono')),
                ('Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminView.carrera')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
