# Generated by Django 4.1.5 on 2023-01-27 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='propuestas',
        ),
        migrations.AddField(
            model_name='propuesta',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminView.carrera'),
            preserve_default=False,
        ),
    ]
