# Generated by Django 4.1.5 on 2023-01-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0002_remove_empresa_propuestas_propuesta_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasolicitud',
            name='nombreEmpresa',
            field=models.CharField(max_length=50, verbose_name='nombre de empresa'),
        ),
        migrations.AlterField(
            model_name='empresasolicitud',
            name='nombreProyecto',
            field=models.CharField(max_length=50, verbose_name='nombre de proyecto'),
        ),
    ]
