# Generated by Django 4.1.5 on 2023-02-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0003_alter_empresasolicitud_nombreempresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='nombreAlumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminView.alumno'),
            preserve_default=False,
        ),
    ]
