# Generated by Django 4.1.5 on 2023-02-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0004_propuesta_nombrealumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='nombreAlumno',
        ),
    ]
