# Generated by Django 4.1.5 on 2023-02-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0005_remove_propuesta_nombrealumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='requisitos',
            field=models.TextField(blank=True, verbose_name='requisitos'),
        ),
    ]
