# Generated by Django 4.1.5 on 2023-03-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0006_propuesta_requisitos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='Carrera',
            new_name='carrera',
        ),
        migrations.AddField(
            model_name='empresasolicitud',
            name='tipoCarrera',
            field=models.CharField(default=1, max_length=50, verbose_name='tipo de carrera'),
            preserve_default=False,
        ),
    ]
