# Generated by Django 4.1.5 on 2023-03-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0007_rename_carrera_alumno_carrera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='contrasenia',
            field=models.CharField(default=1, help_text='Contraseña del alumno', max_length=20, verbose_name='Matricula'),
            preserve_default=False,
        ),
    ]
