# Generated by Django 4.1.5 on 2023-03-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0008_alumno_contrasenia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='carrera',
            new_name='Carrera',
        ),
    ]
