# Generated by Django 4.1.5 on 2023-03-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0009_rename_carrera_alumno_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='contrasenia',
            field=models.TextField(verbose_name='requisitos'),
        ),
    ]
