# Generated by Django 4.1.5 on 2023-03-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0011_alter_empresasolicitud_tipocarrera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresasolicitud',
            old_name='tipoCarrera',
            new_name='Carrera',
        ),
    ]
