# Generated by Django 4.1.5 on 2023-03-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0012_rename_tipocarrera_empresasolicitud_carrera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresasolicitud',
            old_name='Carrera',
            new_name='tipoCarrera',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminView.carrera'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminView.carrera'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='nombreEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminView.empresa'),
        ),
    ]
