# Generated by Django 4.1.5 on 2023-03-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0013_rename_carrera_empresasolicitud_tipocarrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasolicitud',
            name='tipoCarrera',
            field=models.CharField(max_length=100, verbose_name='Cnombre'),
        ),
    ]
