# Generated by Django 4.1.5 on 2023-03-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0014_alter_empresasolicitud_tipocarrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasolicitud',
            name='tipoCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminView.carrera'),
        ),
    ]
