# Generated by Django 4.1.5 on 2023-03-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0016_rename_tipocarrera_empresasolicitud_carrera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresasolicitud',
            old_name='Carrera',
            new_name='carrera',
        ),
    ]
