# Generated by Django 4.1.5 on 2023-06-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0017_rename_carrera_empresasolicitud_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasolicitud',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
