# Generated by Django 4.1.5 on 2023-06-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0018_empresasolicitud_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='adminView.carrera'),
            preserve_default=False,
        ),
    ]
