# Generated by Django 4.1.5 on 2023-06-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0019_empresa_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='requisitos',
        ),
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propuesta',
            name='modalidad',
            field=models.CharField(blank=True, max_length=50, verbose_name='modalidad'),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='nombreConsultante',
            field=models.CharField(default='juan', max_length=100, verbose_name='Cnombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propuesta',
            name='puesto',
            field=models.CharField(default='dev jr', help_text='puesto laboral', max_length=50, verbose_name='puesto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propuesta',
            name='telefono',
            field=models.CharField(default='789797', max_length=50, verbose_name='telefono'),
            preserve_default=False,
        ),
    ]
