# Generated by Django 4.1.5 on 2023-06-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0020_remove_propuesta_requisitos_empresa_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasolicitud',
            name='aceptada',
            field=models.BooleanField(default=False, verbose_name='aceptada'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='nombreConsultante',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cnombre'),
        ),
    ]
