# Generated by Django 4.1.5 on 2023-06-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0021_empresasolicitud_aceptada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='alta',
            field=models.BooleanField(default=False, verbose_name='alta'),
        ),
    ]
