# Generated by Django 4.1.5 on 2023-06-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminView', '0023_empresasolicitud_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='nombreEmpresa',
            field=models.CharField(max_length=50, verbose_name='nombreEmpresa'),
        ),
    ]
